package questions;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.StringTokenizer;

public class fluency extends question{
    private String Date[];
    private String day;

    public fluency(){

        this.num = 1000;
        this.quiz = new ArrayList<>();
        this.crr_ans = new ArrayList[this.num];
        for (int i = 0; i < this.num; i++) {
            this.crr_ans[i] = new ArrayList<>();
        }
        this.user_ans = new String[this.num];
        this.scores = new int[10];
        this.Tscore = new Integer(0);

        this.quiz.add("지금부터 제가 그만이라고 말할 때까지 과일이나 채소를 최대한 많이 이야기해 주세요.");
        this.quiz.add("준비되셨지요?");
        this.quiz.add("자, 과일이나 채소 이름을 말씀해 주세요.");
        this.quiz.add("시작!");

        this.crr_ans[0].add("체리");
        this.crr_ans[0].add("자두");
        this.crr_ans[0].add("딸기");
        this.crr_ans[0].add("오렌지");
        this.crr_ans[0].add("사과");
        this.crr_ans[0].add("키위");
        this.crr_ans[0].add("메론");
        this.crr_ans[0].add("포도");
        this.crr_ans[0].add("버찌");
        this.crr_ans[0].add("야자");
        this.crr_ans[0].add("복숭아");
        this.crr_ans[0].add("코코넛");
        this.crr_ans[0].add("레몬");
        this.crr_ans[0].add("수박");
        this.crr_ans[0].add("망고");
        this.crr_ans[0].add("홍시");
        this.crr_ans[0].add("감");
        this.crr_ans[0].add("머루");
        this.crr_ans[0].add("자몽");
        this.crr_ans[0].add("살구");
        this.crr_ans[0].add("리치");
        this.crr_ans[0].add("다래");
        this.crr_ans[0].add("모과");
        this.crr_ans[0].add("용과");
        this.crr_ans[0].add("거봉");
        this.crr_ans[0].add("유자");
        this.crr_ans[0].add("베리");
        this.crr_ans[0].add("매실");
        this.crr_ans[0].add("바나나");
        this.crr_ans[0].add("석류");
        this.crr_ans[0].add("대추");
        this.crr_ans[0].add("단감");
        this.crr_ans[0].add("슈가애플");
        this.crr_ans[0].add("망고스틴");
        this.crr_ans[0].add("두리안");
        this.crr_ans[0].add("산딸기");
        this.crr_ans[0].add("아보카도");
        this.crr_ans[0].add("구아바");
        this.crr_ans[0].add("무화과");
        this.crr_ans[0].add("파파야");
        this.crr_ans[0].add("블루베리");
        this.crr_ans[0].add("파인애플");
        this.crr_ans[0].add("한라봉");
        this.crr_ans[0].add("레드향");
        this.crr_ans[0].add("황금향");
        this.crr_ans[0].add("귤");
        this.crr_ans[0].add("금귤");
        this.crr_ans[0].add("천혜향");
        this.crr_ans[0].add("스타후르츠");
        this.crr_ans[0].add("스타후루츠");
        this.crr_ans[0].add("스타프룻");
        this.crr_ans[0].add("스타프루츠");
        this.crr_ans[0].add("블림빙");
        this.crr_ans[0].add("잠부");
        this.crr_ans[0].add("오미자");
        this.crr_ans[0].add("구기자");
        this.crr_ans[0].add("끌렝깽");
        this.crr_ans[0].add("사워");
        this.crr_ans[0].add("감자");
        this.crr_ans[0].add("고구마");
        this.crr_ans[0].add("깻잎");
        this.crr_ans[0].add("당근");
        this.crr_ans[0].add("당귀");
        this.crr_ans[0].add("케일");
        this.crr_ans[0].add("도라지");
        this.crr_ans[0].add("대파");
        this.crr_ans[0].add("마늘");
        this.crr_ans[0].add("무");
        this.crr_ans[0].add("미나리");
        this.crr_ans[0].add("버섯");
        this.crr_ans[0].add("배추");
        this.crr_ans[0].add("부추");
        this.crr_ans[0].add("고추");
        this.crr_ans[0].add("브로콜리");
        this.crr_ans[0].add("생강");
        this.crr_ans[0].add("시금치");
        this.crr_ans[0].add("연근");
        this.crr_ans[0].add("우엉");
        this.crr_ans[0].add("양파");
        this.crr_ans[0].add("양배추");
        this.crr_ans[0].add("호박");
        this.crr_ans[0].add("깻잎");
        this.crr_ans[0].add("옥수수");
        this.crr_ans[0].add("청경채");
        this.crr_ans[0].add("가지");
        this.crr_ans[0].add("실파");
        this.crr_ans[0].add("호박");
        this.crr_ans[0].add("오이");
        this.crr_ans[0].add("양송이");
        this.crr_ans[0].add("무청");
        this.crr_ans[0].add("파");
        this.crr_ans[0].add("실파");
        this.crr_ans[0].add("쪽파");
        this.crr_ans[0].add("양배추");
        this.crr_ans[0].add("양상추");
        this.crr_ans[0].add("바질");
        this.crr_ans[0].add("마늘");
        this.crr_ans[0].add("인삼");
        this.crr_ans[0].add("피망");
        this.crr_ans[0].add("콩나물");
        this.crr_ans[0].add("쑥갓");
        this.crr_ans[0].add("애호박");
        this.crr_ans[0].add("단호박");
        this.crr_ans[0].add("갓");
        this.crr_ans[0].add("다채");
        this.crr_ans[0].add("적채");
        this.crr_ans[0].add("적상추");
        this.crr_ans[0].add("신선초");
        this.crr_ans[0].add("봄동");
        this.crr_ans[0].add("머위");
        this.crr_ans[0].add("아욱");
        this.crr_ans[0].add("우엉");
        this.crr_ans[0].add("더덕");
        this.crr_ans[0].add("죽순");
        this.crr_ans[0].add("청치커리");
        this.crr_ans[0].add("적치커리");
        this.crr_ans[0].add("치커리");
        this.crr_ans[0].add("파프리카");
        this.crr_ans[0].add("파슬리");
        this.crr_ans[0].add("방울토마토");
        this.crr_ans[0].add("토마토");
        this.crr_ans[0].add("비트");
        this.crr_ans[0].add("콜라비");
        this.crr_ans[0].add("라디치오");
        this.crr_ans[0].add("라디키오");
        this.crr_ans[0].add("쌈케일");
        this.crr_ans[0].add("로메인");
        this.crr_ans[0].add("오크라");
        this.crr_ans[0].add("오크리프");
        this.crr_ans[0].add("적겨자");
        this.crr_ans[0].add("청겨자");
        this.crr_ans[0].add("근대");
        this.crr_ans[0].add("경수채");
        this.crr_ans[0].add("순무");
        this.crr_ans[0].add("블랙래디시");
        this.crr_ans[0].add("돼지감자");
        this.crr_ans[0].add("와사비");
        this.crr_ans[0].add("고수");
    }
}
